# Configuración para usar la Base de Datos H2 en memoria
spring.messages.basename=messages
spring.messages.encoding=UTF-8
spring.messages.cache-duration=3600

spring.datasource.url=jdbc:h2:mem:game_and_grill_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# Permite que Spring cree las tablas automáticamente basándose en tu Partida.java
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Activar la consola web de H2 para que puedas ver y meter datos desde el navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Indicar a Spring dónde buscar los archivos de mensajes
spring.messages.basename=messages
spring.messages.fallback-to-system-locale=false
# Asegurar codificación UTF-8
spring.messages.encoding=UTF-8
# Tiempo de caché (0 para que los cambios se vean al momento sin reiniciar)
spring.messages.cache-duration=0